sudo: false

matrix:
  fast_finish: true
  include:
    - python: "3.6"
      env: TOXENV=lint
    - python: "3.6"
      env: TOXENV=pylint

branches:
  only:
    - master

install: pip install -r requirements.txt
language: python

script: tox
